networks:
  go-asynq:
    driver: bridge

services:
  redis:
    container_name: go-asynq_redis
    image: redis:7.2.3
    restart: always
    env_file:
      - .env
    networks:
      - go-asynq
    ports:
      - ${REDIS_PORT}:6379

  queue:
    container_name: go-asynq_queue
    image: agungsptr/go-asynq_queue:1.0
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    networks:
      - go-asynq
    